// 列车长信息
export interface Conductor {
  id: string
  name: string
  department: string
}

// 增强的列车长信息（扩展状态管理）
export interface EnhancedConductor extends Conductor {
  employeeId: string  // 工号
  status: '正式启用' | '临时启用' | '后备' | '免职'
  note?: string
  joinDate?: string      // 入职日期
  enableDate?: string    // 启用日期
  lastStatusChange?: number
  createdAt: number
  updatedAt?: number
  
  // 保持现有字段兼容
  rewardAmount?: number  // 奖励金额
  rewardBase?: number    // 奖励基数
  monthlyScore?: number  // 月度评分
}

// 申请管理
export interface ConductorApplication {
  id: string
  type: '正式启用' | '临时启用' | '免职'
  employeeId: string
  applicantName: string
  currentDepartment: string
  targetDepartment?: string
  applicationDate: string
  status: '待处理' | '已通过' | '已拒绝'
  approver?: string
  approvalDate?: string
  note?: string
  createdAt: number
  updatedAt?: number
}

// 异动记录
export interface PersonnelChange {
  id: string
  employeeId: string
  employeeName: string
  changeType: '状态变更' | '部门调动' | '职务调整' | '入职' | '离职' | '其他'
  fromStatus?: string
  toStatus?: string
  fromDepartment?: string
  toDepartment?: string
  fromPosition?: string
  toPosition?: string
  changeDate: string
  reason: string
  operator: string
  notes?: string
  createdAt: number
  updatedAt: number
  relatedApplicationId?: string // 关联的申请ID
  isAutoGenerated: boolean // 是否自动生成（申请通过时自动创建）
}

// 申请配置
export interface ApplicationSettings {
  tempPeriod: number  // 临时启用期限（月）
  autoExpiry: boolean  // 自动过期处理
  approvalRequired: boolean  // 是否需要审批
}

// 月度数据
export interface MonthlyData {
  id: string
  year: number
  month: number
  data: ConductorMonthlyData[]
}

// 列车长月度数据
export interface ConductorMonthlyData {
  id: string
  name: string
  department: string
  rewardAmount: number
  rewardBase: number
  monthlyScore: number
  isActive: boolean
  status: '在岗' | '不在岗' | '助勤' | '待确认'
}

// 考核记录
export interface AssessmentRecord {
  id: string
  assessDate: string
  assessDeptType: '科室' | '车队' | '其他'
  assessTime: string
  assessorDepartmentName: string
  assessorPerson: string
  baseScore: number
  conductorId: string
  conductorName: string
  department: string
  finalScore: number
  totalScore: number
  totalDeduction: number
  details: AssessmentDetail[]
  remarks?: string
  createdAt: number
  updatedAt?: number
}

// 考核详情
export interface AssessmentDetail {
  assessDeptType: string
  assessorDepartment: string
  deduction: number
  item: string
  itemCategory: string
  itemCode: string
  itemDetail: string
  itemName?: string
  times: number
  length: number
}

// 标准考核项
export interface StandardAssessmentItem {
  id: string
  userCode?: string  // 自定义编号
  name: string
  category: string
  maxScore: number
  description: string
  responsibleDepartment: string  // 原始负责部门
  defaultResponsibleEntities: Array<{
    level: '科室' | '车队'
    department: string
  }>
  createdAt?: number
  updatedAt?: number
}

// 部门信息
export interface Department {
  name: string
  level: '科室' | '车队' | '其他'
  category?: '高铁' | '动车' | '普速' | '其他'
  staff: DepartmentStaff[]
}

// 部门人员
export interface DepartmentStaff {
  id: string
  name: string
  role: string
}

// 系统设置
export interface Settings {
  showInactive: boolean
  highlightAnomaly: boolean
  assessmentPassScore: number
  assessmentExcellentScore: number
  assessmentMaxScore: number
  lastSaved?: number
}

// 数据库结构
export interface Database {
  conductorDB: Record<string, Conductor>
  monthlyData: MonthlyData[]
  departmentCategories: Record<string, string>
  settings: Settings
  standardAssessmentItems: Record<string, StandardAssessmentItem>
  departments: Record<string, Department>
  assessmentDetails: any[]
  assessmentDB: Record<string, AssessmentRecord[]>
  
  // 新增：考核项目类别映射表
  categoryMappings?: {
    itemMappings: Record<string, string>
  }
  
  // 新增：人员管理相关数据
  enhancedConductors?: Record<string, EnhancedConductor>
  applications?: Record<string, ConductorApplication[]>
  personnelChanges?: PersonnelChange[]
  applicationSettings?: ApplicationSettings
} 