<template>
  <div class="personnel-changes">
    <!-- 操作栏 -->
    <div class="action-bar">
      <div class="left-actions">
        <el-button type="primary" @click="openAddDialog">
          <el-icon><Plus /></el-icon>
          新增异动记录
        </el-button>
        <el-button @click="exportChanges">
          <el-icon><Download /></el-icon>
          导出记录
        </el-button>

      </div>
      
      <div class="right-actions">
        <el-tooltip content="显示/隐藏自动生成的记录" placement="top">
          <el-switch
            v-model="showAutoGenerated"
            active-text="显示自动"
            inactive-text="隐藏自动"
            @change="handleFilter"
          />
        </el-tooltip>
      </div>
    </div>

    <!-- 筛选栏 -->
    <div class="filter-bar">
      <el-input 
        v-model="searchQuery" 
        placeholder="搜索工号或姓名"
        prefix-icon="Search"
        clearable
        style="width: 200px"
        @input="handleFilter"
      />
      <el-select 
        v-model="selectedChangeType" 
        placeholder="异动类型" 
        clearable
        style="width: 150px"
        @change="handleFilter"
      >
        <el-option label="状态变更" value="状态变更" />
        <el-option label="部门调动" value="部门调动" />
        <el-option label="职务调整" value="职务调整" />
        <el-option label="入职" value="入职" />
        <el-option label="离职" value="离职" />
        <el-option label="其他" value="其他" />
      </el-select>
      <el-select 
        v-model="selectedDepartment" 
        placeholder="相关部门" 
        clearable
        style="width: 150px"
        @change="handleFilter"
      >
        <el-option v-for="dept in departments" :key="dept" :label="dept" :value="dept" />
      </el-select>
      <el-date-picker 
        v-model="dateRange"
        type="daterange"
        range-separator="至"
        start-placeholder="开始日期"
        end-placeholder="结束日期"
        style="width: 240px"
        @change="handleFilter"
      />
      <el-button @click="resetFilters">重置</el-button>
    </div>

    <!-- 统计信息 -->
    <div class="statistics-bar" v-if="isFiltered">
      <el-alert :closable="false" type="info">
        <template #title>
          <span>筛选结果：从 {{ personnelStore.personnelChanges.length }} 条记录中筛选出 {{ filteredChanges.length }} 条</span>
          <span class="ml-4">
            状态变更: {{ filteredStatistics.状态变更 }} | 
            部门调动: {{ filteredStatistics.部门调动 }} | 
            其他: {{ filteredStatistics.其他 }}
          </span>
        </template>
      </el-alert>
    </div>

    <!-- 异动记录统计卡片 -->
    <div class="stats-cards" v-if="!isFiltered">
      <el-row :gutter="16">
        <el-col :xs="24" :sm="12" :md="6">
          <el-card class="stats-card">
            <div class="stats-content">
              <div class="stats-icon">
                <el-icon><Files /></el-icon>
              </div>
              <div class="stats-info">
                <div class="stats-value">{{ changeStats.total }}</div>
                <div class="stats-label">总记录数</div>
              </div>
            </div>
          </el-card>
        </el-col>
        <el-col :xs="24" :sm="12" :md="6">
          <el-card class="stats-card">
            <div class="stats-content">
              <div class="stats-icon auto">
                <el-icon><Setting /></el-icon>
              </div>
              <div class="stats-info">
                <div class="stats-value">{{ changeStats.autoGenerated }}</div>
                <div class="stats-label">自动生成</div>
              </div>
            </div>
          </el-card>
        </el-col>
        <el-col :xs="24" :sm="12" :md="6">
          <el-card class="stats-card">
            <div class="stats-content">
              <div class="stats-icon manual">
                <el-icon><EditPen /></el-icon>
              </div>
              <div class="stats-info">
                <div class="stats-value">{{ changeStats.manual }}</div>
                <div class="stats-label">手动添加</div>
              </div>
            </div>
          </el-card>
        </el-col>
        <el-col :xs="24" :sm="12" :md="6">
          <el-card class="stats-card">
            <div class="stats-content">
              <div class="stats-icon recent">
                <el-icon><Clock /></el-icon>
              </div>
              <div class="stats-info">
                <div class="stats-value">{{ recentChangesCount }}</div>
                <div class="stats-label">本月新增</div>
              </div>
            </div>
          </el-card>
        </el-col>
      </el-row>
    </div>

    <!-- 异动记录列表 -->
    <div class="changes-list" v-loading="personnelStore.loading">
      <template v-if="paginatedChanges.length === 0">
        <el-empty description="暂无异动记录" />
      </template>
      
      <template v-else>
        <!-- 时间线视图 -->
        <el-timeline class="changes-timeline">
          <el-timeline-item
            v-for="change in paginatedChanges"
            :key="change.id"
            :timestamp="formatDateTime(change.createdAt)"
            :type="getTimelineType(change.changeType)"
            :icon="getTimelineIcon(change.changeType)"
            size="large"
          >
            <el-card class="change-card" shadow="hover">
              <!-- 异动头部 -->
              <div class="change-header">
                <div class="left-section">
                  <div class="employee-info">
                    <span class="employee-name">{{ change.employeeName }}</span>
                    <span class="employee-id">（{{ change.employeeId }}）</span>
                  </div>
                  <el-tag 
                    :type="getChangeTypeColor(change.changeType)" 
                    size="small"
                    class="change-type-tag"
                  >
                    {{ change.changeType }}
                  </el-tag>
                </div>
                
                <div class="right-section">
                  <el-tag 
                    v-if="change.isAutoGenerated" 
                    type="info" 
                    size="small"
                    class="auto-tag"
                  >
                    自动生成
                  </el-tag>
                  <div class="change-actions">
                    <el-button 
                      v-if="!change.isAutoGenerated"
                      type="primary" 
                      size="small" 
                      text
                      @click="editChange(change)"
                    >
                      <el-icon><Edit /></el-icon>
                      编辑
                    </el-button>
                    <el-button 
                      v-if="!change.isAutoGenerated"
                      type="danger" 
                      size="small" 
                      text
                      @click="deleteChange(change.id)"
                    >
                      <el-icon><Delete /></el-icon>
                      删除
                    </el-button>
                    <el-button 
                      type="info" 
                      size="small" 
                      text
                      @click="viewDetail(change)"
                    >
                      <el-icon><View /></el-icon>
                      详情
                    </el-button>
                  </div>
                </div>
              </div>

              <!-- 异动内容 -->
              <div class="change-content">
                <div class="change-summary">
                  <span class="change-desc">{{ getChangeDescription(change) }}</span>
                </div>
                
                <div class="change-details">
                  <div class="detail-item" v-if="change.reason">
                    <span class="label">异动原因：</span>
                    <span class="value">{{ change.reason }}</span>
                  </div>
                  <div class="detail-item">
                    <span class="label">操作人：</span>
                    <span class="value">{{ change.operator }}</span>
                  </div>
                  <div class="detail-item">
                    <span class="label">异动日期：</span>
                    <span class="value">{{ formatDate(change.changeDate) }}</span>
                  </div>
                  <div class="detail-item" v-if="change.notes">
                    <span class="label">备注：</span>
                    <span class="value notes">{{ change.notes }}</span>
                  </div>
                </div>
              </div>
            </el-card>
          </el-timeline-item>
        </el-timeline>

        <!-- 分页 -->
        <div class="pagination-wrapper">
          <el-pagination
            v-model:current-page="currentPage"
            v-model:page-size="pageSize"
            :total="filteredChanges.length"
            :page-sizes="[10, 20, 50, 100]"
            layout="total, sizes, prev, pager, next, jumper"
            @size-change="handleSizeChange"
            @current-change="handleCurrentChange"
          />
        </div>
      </template>
    </div>

    <!-- 新增/编辑异动记录对话框 -->
    <el-dialog 
      v-model="dialogVisible" 
      :title="isEditing ? '编辑异动记录' : '新增异动记录'"
      width="600px"
      @closed="resetForm"
    >
      <el-form 
        ref="formRef" 
        :model="form" 
        :rules="formRules"
        label-width="100px"
      >
        <el-form-item label="工号" prop="employeeId">
          <el-input 
            v-model="form.employeeId" 
            placeholder="输入工号查找人员"
            @blur="lookupEmployee"
            :disabled="isEditing"
          >
            <template #append>
              <el-button @click="lookupEmployee" :icon="Search" :disabled="isEditing">查找</el-button>
            </template>
          </el-input>
        </el-form-item>
        
        <el-form-item label="姓名">
          <el-input v-model="form.employeeName" readonly />
        </el-form-item>
        
        <el-form-item label="异动类型" prop="changeType">
          <el-select v-model="form.changeType" style="width: 100%" @change="handleChangeTypeChange">
            <el-option label="状态变更" value="状态变更" />
            <el-option label="部门调动" value="部门调动" />
            <el-option label="职务调整" value="职务调整" />
            <el-option label="入职" value="入职" />
            <el-option label="离职" value="离职" />
            <el-option label="其他" value="其他" />
          </el-select>
        </el-form-item>
        
        <!-- 状态变更字段 -->
        <template v-if="form.changeType === '状态变更'">
          <el-form-item label="原状态">
            <el-input v-model="form.fromStatus" placeholder="请输入原状态" />
          </el-form-item>
          <el-form-item label="新状态">
            <el-input v-model="form.toStatus" placeholder="请输入新状态" />
          </el-form-item>
        </template>
        
        <!-- 部门调动字段 -->
        <template v-if="form.changeType === '部门调动'">
          <el-form-item label="原部门">
            <el-select v-model="form.fromDepartment" placeholder="请选择原部门" clearable style="width: 100%">
              <el-option v-for="dept in departments" :key="dept" :label="dept" :value="dept" />
            </el-select>
          </el-form-item>
          <el-form-item label="新部门">
            <el-select v-model="form.toDepartment" placeholder="请选择新部门" clearable style="width: 100%">
              <el-option v-for="dept in departments" :key="dept" :label="dept" :value="dept" />
            </el-select>
          </el-form-item>
        </template>
        
        <!-- 职务调整字段 -->
        <template v-if="form.changeType === '职务调整'">
          <el-form-item label="原职务">
            <el-input v-model="form.fromPosition" placeholder="请输入原职务" />
          </el-form-item>
          <el-form-item label="新职务">
            <el-input v-model="form.toPosition" placeholder="请输入新职务" />
          </el-form-item>
        </template>
        
        <el-form-item label="异动日期" prop="changeDate">
          <el-date-picker 
            v-model="form.changeDate"
            type="date"
            placeholder="选择异动日期"
            style="width: 100%"
          />
        </el-form-item>
        
        <el-form-item label="异动原因" prop="reason">
          <el-input 
            v-model="form.reason"
            type="textarea"
            :rows="3"
            placeholder="请输入异动原因"
            maxlength="200"
            show-word-limit
          />
        </el-form-item>
        
        <el-form-item label="备注">
          <el-input 
            v-model="form.notes"
            type="textarea"
            :rows="2"
            placeholder="请输入备注信息（可选）"
            maxlength="200"
            show-word-limit
          />
        </el-form-item>
      </el-form>
      
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="submitForm" :loading="personnelStore.loading">
          {{ isEditing ? '更新' : '保存' }}
        </el-button>
      </template>
    </el-dialog>

    <!-- 详情对话框 -->
    <el-dialog v-model="detailDialogVisible" title="异动记录详情" width="500px">
      <div v-if="selectedChange" class="change-detail">
        <el-descriptions :column="1" border>
          <el-descriptions-item label="异动类型">
            <el-tag :type="getChangeTypeColor(selectedChange.changeType)">
              {{ selectedChange.changeType }}
            </el-tag>
          </el-descriptions-item>
          <el-descriptions-item label="员工信息">
            {{ selectedChange.employeeName }}（{{ selectedChange.employeeId }}）
          </el-descriptions-item>
          <el-descriptions-item label="异动详情">
            {{ getChangeDescription(selectedChange) }}
          </el-descriptions-item>
          <el-descriptions-item label="异动日期">
            {{ formatDate(selectedChange.changeDate) }}
          </el-descriptions-item>
          <el-descriptions-item label="异动原因">
            {{ selectedChange.reason }}
          </el-descriptions-item>
          <el-descriptions-item label="操作人">
            {{ selectedChange.operator }}
          </el-descriptions-item>
          <el-descriptions-item label="记录类型">
            <el-tag :type="selectedChange.isAutoGenerated ? 'info' : 'success'" size="small">
              {{ selectedChange.isAutoGenerated ? '自动生成' : '手动添加' }}
            </el-tag>
          </el-descriptions-item>
          <el-descriptions-item label="备注" v-if="selectedChange.notes">
            {{ selectedChange.notes }}
          </el-descriptions-item>
          <el-descriptions-item label="创建时间">
            {{ formatDateTime(selectedChange.createdAt) }}
          </el-descriptions-item>
          <el-descriptions-item label="更新时间" v-if="selectedChange.updatedAt !== selectedChange.createdAt">
            {{ formatDateTime(selectedChange.updatedAt) }}
          </el-descriptions-item>
        </el-descriptions>
      </div>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { 
  Plus, 
  Download, 
  Search, 
  Edit, 
  Delete, 
  View, 
  Files, 
  Setting, 
  EditPen, 
  Clock,
  User,
  Switch,
  Promotion,
  UserFilled,
  RemoveFilled
} from '@element-plus/icons-vue'
import { usePersonnelStore } from '@/stores/personnel'
import { useApplicationStore } from '@/stores/applications'
import { useMainStore } from '@/stores'
import type { PersonnelChange } from '@/types'

// Store实例
const personnelStore = usePersonnelStore()
const applicationStore = useApplicationStore()
const mainStore = useMainStore()

// 响应式数据
const searchQuery = ref('')
const selectedChangeType = ref('')
const selectedDepartment = ref('')
const dateRange = ref<[Date, Date]>()
const showAutoGenerated = ref(true)
const currentPage = ref(1)
const pageSize = ref(10)

// 对话框相关
const dialogVisible = ref(false)
const detailDialogVisible = ref(false)
const isEditing = ref(false)
const selectedChange = ref<PersonnelChange | null>(null)
const formRef = ref()

// 表单数据
const form = ref({
  employeeId: '',
  employeeName: '',
  changeType: '',
  fromStatus: '',
  toStatus: '',
  fromDepartment: '',
  toDepartment: '',
  fromPosition: '',
  toPosition: '',
  changeDate: new Date(),
  reason: '',
  notes: '',
  operator: '管理员'
})

// 表单验证规则
const formRules = {
  employeeId: [
    { required: true, message: '请输入工号', trigger: 'blur' }
  ],
  changeType: [
    { required: true, message: '请选择异动类型', trigger: 'change' }
  ],
  changeDate: [
    { required: true, message: '请选择异动日期', trigger: 'change' }
  ],
  reason: [
    { required: true, message: '请输入异动原因', trigger: 'blur' }
  ]
}

// 计算属性
const departments = computed(() => mainStore.departments)

const filteredChanges = computed(() => {
  const filters = {
    employeeId: searchQuery.value,
    changeType: selectedChangeType.value,
    department: selectedDepartment.value,
    dateRange: dateRange.value ? [
      dateRange.value[0].toISOString().split('T')[0],
      dateRange.value[1].toISOString().split('T')[0]
    ] as [string, string] : undefined,
    isAutoGenerated: showAutoGenerated.value ? undefined : false
  }
  
  return personnelStore.getPersonnelChanges(filters)
})

const paginatedChanges = computed(() => {
  const start = (currentPage.value - 1) * pageSize.value
  const end = start + pageSize.value
  return filteredChanges.value.slice(start, end)
})

const isFiltered = computed(() => {
  return searchQuery.value !== '' || 
         selectedChangeType.value !== '' || 
         selectedDepartment.value !== '' || 
         dateRange.value !== undefined ||
         !showAutoGenerated.value
})

const filteredStatistics = computed(() => {
  const stats = {
    状态变更: 0,
    部门调动: 0,
    职务调整: 0,
    入职: 0,
    离职: 0,
    其他: 0
  }
  
  filteredChanges.value.forEach(change => {
    stats[change.changeType as keyof typeof stats]++
  })
  
  return stats
})

const changeStats = computed(() => personnelStore.getPersonnelChangeStatistics())

const recentChangesCount = computed(() => {
  const currentMonth = new Date().toISOString().slice(0, 7)
  return personnelStore.personnelChanges.filter(change => 
    change.changeDate.startsWith(currentMonth)
  ).length
})

// 方法
const handleFilter = () => {
  currentPage.value = 1
}

const resetFilters = () => {
  searchQuery.value = ''
  selectedChangeType.value = ''
  selectedDepartment.value = ''
  dateRange.value = undefined
  showAutoGenerated.value = true
  currentPage.value = 1
}

const handleSizeChange = (size: number) => {
  pageSize.value = size
  currentPage.value = 1
}

const handleCurrentChange = (page: number) => {
  currentPage.value = page
}

// 对话框相关方法
const openAddDialog = () => {
  isEditing.value = false
  dialogVisible.value = true
  form.value.changeDate = new Date()
}

const editChange = (change: PersonnelChange) => {
  isEditing.value = true
  selectedChange.value = change
  
  // 填充表单
  form.value = {
    employeeId: change.employeeId,
    employeeName: change.employeeName,
    changeType: change.changeType,
    fromStatus: change.fromStatus || '',
    toStatus: change.toStatus || '',
    fromDepartment: change.fromDepartment || '',
    toDepartment: change.toDepartment || '',
    fromPosition: change.fromPosition || '',
    toPosition: change.toPosition || '',
    changeDate: new Date(change.changeDate),
    reason: change.reason,
    notes: change.notes || '',
    operator: change.operator
  }
  
  dialogVisible.value = true
}

const resetForm = () => {
  form.value = {
    employeeId: '',
    employeeName: '',
    changeType: '',
    fromStatus: '',
    toStatus: '',
    fromDepartment: '',
    toDepartment: '',
    fromPosition: '',
    toPosition: '',
    changeDate: new Date(),
    reason: '',
    notes: '',
    operator: '管理员'
  }
  formRef.value?.resetFields()
}

const lookupEmployee = () => {
  const employeeId = form.value.employeeId.trim()
  if (!employeeId) {
    ElMessage.warning('请输入工号')
    return
  }
  
  const conductor = personnelStore.getConductorByEmployeeId(employeeId)
  if (!conductor) {
    ElMessage.error('未找到该工号对应的列车长')
    form.value.employeeName = ''
    return
  }
  
  // 填充表单
  form.value.employeeName = conductor.name
}

const handleChangeTypeChange = () => {
  // 清空相关字段
  form.value.fromStatus = ''
  form.value.toStatus = ''
  form.value.fromDepartment = ''
  form.value.toDepartment = ''
  form.value.fromPosition = ''
  form.value.toPosition = ''
}

const submitForm = async () => {
  try {
    await formRef.value?.validate()
    
    const changeData = {
      employeeId: form.value.employeeId,
      employeeName: form.value.employeeName,
      changeType: form.value.changeType as PersonnelChange['changeType'],
      fromStatus: form.value.fromStatus || undefined,
      toStatus: form.value.toStatus || undefined,
      fromDepartment: form.value.fromDepartment || undefined,
      toDepartment: form.value.toDepartment || undefined,
      fromPosition: form.value.fromPosition || undefined,
      toPosition: form.value.toPosition || undefined,
      changeDate: form.value.changeDate.toISOString().split('T')[0],
      reason: form.value.reason,
      operator: form.value.operator,
      notes: form.value.notes || undefined,
      isAutoGenerated: false
    }
    
    if (isEditing.value && selectedChange.value) {
      await personnelStore.updatePersonnelChange(selectedChange.value.id, changeData)
      ElMessage.success('异动记录更新成功')
    } else {
      await personnelStore.addPersonnelChange(changeData)
      ElMessage.success('异动记录添加成功')
    }
    
    dialogVisible.value = false
    
  } catch (error: any) {
    if (error.message) {
      ElMessage.error(error.message)
    }
  }
}

const deleteChange = async (changeId: string) => {
  try {
    await ElMessageBox.confirm('确定要删除此异动记录吗？此操作无法撤销！', '确认删除', {
      type: 'error'
    })
    
    await personnelStore.deletePersonnelChange(changeId)
    ElMessage.success('异动记录已删除')
    
  } catch (error: any) {
    if (error.message && error.message !== 'cancel') {
      ElMessage.error(error.message)
    }
  }
}

const viewDetail = (change: PersonnelChange) => {
  selectedChange.value = change
  detailDialogVisible.value = true
}

const exportChanges = () => {
  if (filteredChanges.value.length === 0) {
    ElMessage.warning('没有数据可导出')
    return
  }
  
  const exportData = filteredChanges.value.map((change, index) => ({
    序号: index + 1,
    工号: change.employeeId,
    姓名: change.employeeName,
    异动类型: change.changeType,
    异动详情: getChangeDescription(change),
    异动日期: change.changeDate,
    异动原因: change.reason,
    操作人: change.operator,
    记录类型: change.isAutoGenerated ? '自动生成' : '手动添加',
    备注: change.notes || ''
  }))
  
  // 这里可以集成Excel导出功能
  console.log('导出数据:', exportData)
  ElMessage.success('导出功能开发中...')
}

// 工具方法
const getChangeTypeColor = (changeType: string) => {
  switch (changeType) {
    case '状态变更': return 'primary'
    case '部门调动': return 'warning'
    case '职务调整': return 'success'
    case '入职': return 'success'
    case '离职': return 'danger'
    default: return 'info'
  }
}

const getTimelineType = (changeType: string) => {
  switch (changeType) {
    case '状态变更': return 'primary'
    case '部门调动': return 'warning'
    case '职务调整': return 'success'
    case '入职': return 'success'
    case '离职': return 'danger'
    default: return 'info'
  }
}

const getTimelineIcon = (changeType: string) => {
  switch (changeType) {
    case '状态变更': return Switch
    case '部门调动': return Promotion
    case '职务调整': return User
    case '入职': return UserFilled
    case '离职': return RemoveFilled
    default: return EditPen
  }
}

const getChangeDescription = (change: PersonnelChange) => {
  switch (change.changeType) {
    case '状态变更':
      return `${change.fromStatus || '未知'} → ${change.toStatus || '未知'}`
    case '部门调动':
      return `${change.fromDepartment || '未知'} → ${change.toDepartment || '未知'}`
    case '职务调整':
      return `${change.fromPosition || '未知'} → ${change.toPosition || '未知'}`
    case '入职':
      return `加入${change.toDepartment || ''}，初始状态：${change.toStatus || '未知'}`
    case '离职':
      return `离开${change.fromDepartment || ''}，原状态：${change.fromStatus || '未知'}`
    default:
      return '其他异动'
  }
}

const formatDate = (date: string | number) => {
  return new Date(date).toLocaleDateString('zh-CN')
}

const formatDateTime = (timestamp: number) => {
  return new Date(timestamp).toLocaleString('zh-CN')
}

// 生命周期
onMounted(async () => {
  // 首先确保主store数据已加载
  if (!mainStore.database) {
    await mainStore.loadDatabase()
  }
  
  // 初始化加载数据
  personnelStore.loadFromDatabase()
  applicationStore.loadFromDatabase()
})
</script>

<style lang="scss" scoped>
.personnel-changes {
  .action-bar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 16px;
    
    .left-actions, .right-actions {
      display: flex;
      gap: 12px;
      align-items: center;
    }
  }
  
  .filter-bar {
    display: flex;
    gap: 12px;
    align-items: center;
    margin-bottom: 16px;
    padding: 16px;
    background: #f8f9fa;
    border-radius: 8px;
  }
  
  .statistics-bar {
    margin-bottom: 16px;
  }
  
  .stats-cards {
    margin-bottom: 24px;
    
    .stats-card {
      border: none;
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
      
      .stats-content {
        display: flex;
        align-items: center;
        gap: 16px;
        
        .stats-icon {
          width: 48px;
          height: 48px;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          font-size: 20px;
          
          &.auto {
            background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
          }
          
          &.manual {
            background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
          }
          
          &.recent {
            background: linear-gradient(135deg, #43e97b 0%, #38f9d7 100%);
          }
        }
        
        .stats-info {
          flex: 1;
          
          .stats-value {
            font-size: 24px;
            font-weight: 600;
            color: #303133;
            line-height: 1;
          }
          
          .stats-label {
            font-size: 14px;
            color: #909399;
            margin-top: 4px;
          }
        }
      }
    }
  }
  
  .changes-timeline {
    margin-bottom: 32px;
    
    .change-card {
      margin-left: 20px;
      border: 1px solid #e4e7ed;
      transition: all 0.3s ease;
      
      &:hover {
        box-shadow: 0 4px 16px rgba(0, 0, 0, 0.1);
        transform: translateY(-2px);
      }
      
      .change-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 12px;
        
        .left-section {
          display: flex;
          align-items: center;
          gap: 12px;
          
          .employee-info {
            .employee-name {
              font-weight: 500;
              color: #303133;
            }
            
            .employee-id {
              color: #909399;
              font-size: 14px;
            }
          }
          
          .change-type-tag {
            font-weight: 500;
          }
        }
        
        .right-section {
          display: flex;
          align-items: center;
          gap: 8px;
          
          .auto-tag {
            margin-right: 8px;
          }
          
          .change-actions {
            display: flex;
            gap: 4px;
          }
        }
      }
      
      .change-content {
        .change-summary {
          margin-bottom: 12px;
          
          .change-desc {
            font-size: 16px;
            font-weight: 500;
            color: #409eff;
          }
        }
        
        .change-details {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
          gap: 8px;
          
          .detail-item {
            display: flex;
            align-items: flex-start;
            
            .label {
              min-width: 80px;
              color: #909399;
              font-size: 14px;
              margin-right: 8px;
            }
            
            .value {
              color: #303133;
              font-size: 14px;
              
              &.notes {
                line-height: 1.4;
              }
            }
          }
        }
      }
    }
  }
  
  .pagination-wrapper {
    display: flex;
    justify-content: flex-end;
    margin-top: 24px;
  }
  
  .change-detail {
    .el-descriptions {
      :deep(.el-descriptions__label) {
        width: 100px;
      }
    }
  }
}

:deep(.el-timeline-item__timestamp) {
  font-size: 12px;
  color: #909399;
}

:deep(.el-timeline-item__icon) {
  font-size: 16px;
}
</style> 